package co.voik.agesandtheart.worldgen

import net.minecraft.core.registries.Registries
import net.minecraft.server.MinecraftServer
import net.minecraft.world.level.biome.Biomes
import net.minecraft.world.level.biome.FixedBiomeSource
import net.minecraft.world.level.biome.MultiNoiseBiomeSource
import net.minecraft.world.level.biome.MultiNoiseBiomeSourceParameterLists
import net.minecraft.world.level.chunk.ChunkGenerator
import net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator
import net.minecraft.world.level.levelgen.NoiseGeneratorSettings

/**
 * **Tier B — the vanilla delegate.** An Age generated by Minecraft's own pipeline, wrapped whole.
 *
 * Its immediate job is **a reference point for `/age bench`**: measuring our generators in isolation says
 * only whether they got faster, where running vanilla's through the identical harness turns "39 ms/chunk"
 * into a number that can be judged.
 *
 * Two variants, because one alone would mislead. [overworld] is the honest *total* cost of a real world,
 * decoration and all; [bareOverworld] does the same shaping and surfacing over a barren biome, which is
 * the like-for-like comparison while our field Ages skip decoration.
 */
object VanillaDelegate {

    /** Vanilla's overworld, entire: real biomes, features and structures. */
    fun overworld(server: MinecraftServer): ChunkGenerator {
        val parameters = server.registryAccess()
            .lookupOrThrow(Registries.MULTI_NOISE_BIOME_SOURCE_PARAMETER_LIST)
            .getOrThrow(MultiNoiseBiomeSourceParameterLists.OVERWORLD)
        return NoiseBasedChunkGenerator(MultiNoiseBiomeSource.createFromPreset(parameters), overworldSettings(server))
    }

    /**
     * Vanilla's overworld shaping and surfacing over a single barren biome — same pipeline, no
     * decoration. The control against which our own generators are currently comparable.
     */
    fun bareOverworld(server: MinecraftServer): ChunkGenerator {
        val barren = server.registryAccess().lookupOrThrow(Registries.BIOME).getOrThrow(Biomes.THE_VOID)
        return NoiseBasedChunkGenerator(FixedBiomeSource(barren), overworldSettings(server))
    }

    private fun overworldSettings(server: MinecraftServer) =
        server.registryAccess().lookupOrThrow(Registries.NOISE_SETTINGS).getOrThrow(NoiseGeneratorSettings.OVERWORLD)
}
