package co.voik.agesandtheart.worldgen

import net.minecraft.core.registries.Registries
import net.minecraft.server.MinecraftServer
import net.minecraft.world.level.biome.Biomes
import net.minecraft.world.level.biome.FixedBiomeSource
import net.minecraft.world.level.biome.MultiNoiseBiomeSource
import net.minecraft.world.level.biome.MultiNoiseBiomeSourceParameterLists
import net.minecraft.world.level.chunk.ChunkGenerator
import net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator
import net.minecraft.world.level.levelgen.NoiseGeneratorSettings

/**
 * **Tier B — the vanilla delegate.** An Age generated by Minecraft's own pipeline, wrapped whole: a
 * real [NoiseBasedChunkGenerator] on vanilla's overworld noise settings. The architecture always
 * reserved a place for this (`notes/terrain-architecture.md`) — a preset that owns its entire process,
 * chosen at the root, because some worlds want vanilla's fidelity rather than our composition.
 *
 * Its immediate job is narrower: **a reference point for `/age bench`**. Measuring our generators in
 * isolation says nothing about whether they are fast, only whether they got faster. Running vanilla's
 * own generator through the identical harness — same command, same radius, same server, same warmth,
 * equally virgin chunks — turns "39 ms/chunk" into a number that can be judged.
 *
 * Two variants, because one alone would mislead:
 * - [overworld] is the honest *total* cost of a real world — multi-noise biomes, features, structures,
 *   decoration and all. It answers "what does Minecraft charge for a chunk?"
 * - [bareOverworld] runs the same shaping and surfacing over a barren biome, so nothing decorates. That
 *   is the like-for-like comparison **today**, since our field Ages sit on `the_void` and skip
 *   decoration entirely. Expect our worlds to move toward [overworld] as real biomes arrive.
 */
object VanillaDelegate {

    /** Vanilla's overworld, entire: real biomes, features and structures. */
    fun overworld(server: MinecraftServer): ChunkGenerator {
        val parameters = server.registryAccess()
            .lookupOrThrow(Registries.MULTI_NOISE_BIOME_SOURCE_PARAMETER_LIST)
            .getOrThrow(MultiNoiseBiomeSourceParameterLists.OVERWORLD)
        return NoiseBasedChunkGenerator(MultiNoiseBiomeSource.createFromPreset(parameters), overworldSettings(server))
    }

    /**
     * Vanilla's overworld shaping and surfacing over a single barren biome — same pipeline, no
     * decoration. The control against which our own generators are currently comparable.
     */
    fun bareOverworld(server: MinecraftServer): ChunkGenerator {
        val barren = server.registryAccess().lookupOrThrow(Registries.BIOME).getOrThrow(Biomes.THE_VOID)
        return NoiseBasedChunkGenerator(FixedBiomeSource(barren), overworldSettings(server))
    }

    private fun overworldSettings(server: MinecraftServer) =
        server.registryAccess().lookupOrThrow(Registries.NOISE_SETTINGS).getOrThrow(NoiseGeneratorSettings.OVERWORLD)
}
